#!/usr/bin/env bash

echo 'Install JDK'
echo '-----------------'

# to list available jdk, enter brew search jdk

brew cask install adoptopenjdk8
brew cask install adoptopenjdk9
brew cask install adoptopenjdk13

echo '-----------------'
